# Pandas



### Pandas is one of the tools in Machine Learning 
### It is used for data cleaning and analysis. 
### Other features : Exploring, cleaning, transforming and visualizing from data. 
### Pandas is an open-source python package built on top of Numpy

In [1]:
import pandas as pd

In [2]:
a = pd.Series([1,2,3,4,5,6])
a

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
type(a)

pandas.core.series.Series

In [4]:
# excessing elements form series
a[3]

4

In [5]:
a = pd.Series(['a','b','z'])
a

0    a
1    b
2    z
dtype: object

In [6]:
# Date index
date = pd.date_range(start='14-06-2000', end='25-06-2000')
date

DatetimeIndex(['2000-06-14', '2000-06-15', '2000-06-16', '2000-06-17',
               '2000-06-18', '2000-06-19', '2000-06-20', '2000-06-21',
               '2000-06-22', '2000-06-23', '2000-06-24', '2000-06-25'],
              dtype='datetime64[ns]', freq='D')

In [7]:
type(date)

pandas.core.indexes.datetimes.DatetimeIndex

## Pandas Dataframe

In [8]:
# creating array of data
name = ['Deepanshu','Gunjan','Vikrant','Amrita','Neha']

In [9]:
domain = ['AI/ML','Java','JS','Python','AI/ML']

In [10]:
experience = [3,2,4,1,3]

In [11]:
# creating dictonary from array
data = {'Name': name,
        'Domain':domain,
        'Experience':experience
}

In [12]:
# passing dictionary to DataFrame
df = pd.DataFrame(data)
df

Name  Domain  Experience
0  Deepanshu   AI/ML           3
1     Gunjan    Java           2
2    Vikrant      JS           4
3     Amrita  Python           1
4       Neha   AI/ML           3

In [13]:
# zip function: take out values of particular index and make a tuple out of it

zipped = list(zip(name,domain,experience))
zipped

[('Deepanshu', 'AI/ML', 3),
 ('Gunjan', 'Java', 2),
 ('Vikrant', 'JS', 4),
 ('Amrita', 'Python', 1),
 ('Neha', 'AI/ML', 3)]

In [14]:
import numpy as np

In [15]:
a = np.random.random([5,4])
a

array([[0.84457701, 0.25129177, 0.72080224, 0.53598889],
       [0.48854486, 0.34968467, 0.03610767, 0.62779928],
       [0.48503092, 0.75775261, 0.87008454, 0.05008228],
       [0.87102865, 0.12466286, 0.82862685, 0.84919584],
       [0.13393566, 0.90906226, 0.45643549, 0.18419922]])

In [16]:
df1 = pd.DataFrame(a) 
df1

0         1         2         3
0  0.844577  0.251292  0.720802  0.535989
1  0.488545  0.349685  0.036108  0.627799
2  0.485031  0.757753  0.870085  0.050082
3  0.871029  0.124663  0.828627  0.849196
4  0.133936  0.909062  0.456435  0.184199

In [17]:
df1 = pd.DataFrame(data = a, columns='W X Y Z'.split(), index = 'A B C D E'.split())
df1

W         X         Y         Z
A  0.844577  0.251292  0.720802  0.535989
B  0.488545  0.349685  0.036108  0.627799
C  0.485031  0.757753  0.870085  0.050082
D  0.871029  0.124663  0.828627  0.849196
E  0.133936  0.909062  0.456435  0.184199

In [18]:
df1.drop('Z', axis=1)
# axis =1 defines column, bydefault it a row oriented,

W         X         Y
A  0.844577  0.251292  0.720802
B  0.488545  0.349685  0.036108
C  0.485031  0.757753  0.870085
D  0.871029  0.124663  0.828627
E  0.133936  0.909062  0.456435

In [19]:
df1

W         X         Y         Z
A  0.844577  0.251292  0.720802  0.535989
B  0.488545  0.349685  0.036108  0.627799
C  0.485031  0.757753  0.870085  0.050082
D  0.871029  0.124663  0.828627  0.849196
E  0.133936  0.909062  0.456435  0.184199

In [20]:
# if you want drop permanent the use inplace as true
df1.drop('Z', axis=1, inplace = True)
df1

W         X         Y
A  0.844577  0.251292  0.720802
B  0.488545  0.349685  0.036108
C  0.485031  0.757753  0.870085
D  0.871029  0.124663  0.828627
E  0.133936  0.909062  0.456435

In [21]:
#accessing column values by default
df1['W']

A    0.844577
B    0.488545
C    0.485031
D    0.871029
E    0.133936
Name: W, dtype: float64

In [22]:
# location work on index only and provide corresponding values
df1.loc['A']

W    0.844577
X    0.251292
Y    0.720802
Name: A, dtype: float64

In [23]:
# to fetch column or row number wise we use iloc(index loaction)
df1.iloc[2]

W    0.485031
X    0.757753
Y    0.870085
Name: C, dtype: float64

In [24]:
df1.loc['A','W']

0.8445770099907545

In [25]:
df1.loc[['A','B'],['W','X']]

W         X
A  0.844577  0.251292
B  0.488545  0.349685

In [26]:
# pick random numbers in between low and high and shape is given in size
val1 = np.random.randint(low =10,high=90,size=[20,])
val1

array([73, 45, 75, 49, 22, 26, 74, 46, 89, 17, 29, 22, 48, 30, 81, 30, 18,
       22, 60, 78])

In [27]:
# pick passed elements from the given list
val2 = np.random.choice(['Ansh','vans','veer','shiv'],20)
val2

array(['Ansh', 'Ansh', 'shiv', 'Ansh', 'veer', 'Ansh', 'shiv', 'veer',
       'Ansh', 'vans', 'veer', 'shiv', 'veer', 'vans', 'vans', 'vans',
       'shiv', 'Ansh', 'Ansh', 'shiv'], dtype='<U4')

In [28]:
zipped = list(zip(val1,val2))
zipped

[(73, 'Ansh'),
 (45, 'Ansh'),
 (75, 'shiv'),
 (49, 'Ansh'),
 (22, 'veer'),
 (26, 'Ansh'),
 (74, 'shiv'),
 (46, 'veer'),
 (89, 'Ansh'),
 (17, 'vans'),
 (29, 'veer'),
 (22, 'shiv'),
 (48, 'veer'),
 (30, 'vans'),
 (81, 'vans'),
 (30, 'vans'),
 (18, 'shiv'),
 (22, 'Ansh'),
 (60, 'Ansh'),
 (78, 'shiv')]

In [29]:
# creating dataframe
df = pd.DataFrame(data=zipped,columns=['Age','Name'])
df

Age  Name
0    73  Ansh
1    45  Ansh
2    75  shiv
3    49  Ansh
4    22  veer
5    26  Ansh
6    74  shiv
7    46  veer
8    89  Ansh
9    17  vans
10   29  veer
11   22  shiv
12   48  veer
13   30  vans
14   81  vans
15   30  vans
16   18  shiv
17   22  Ansh
18   60  Ansh
19   78  shiv

In [30]:
type(df)

pandas.core.frame.DataFrame

In [31]:
#Default 5 top values
df.head() 

Age  Name
0   73  Ansh
1   45  Ansh
2   75  shiv
3   49  Ansh
4   22  veer

In [32]:
df.head(2)

Age  Name
0   73  Ansh
1   45  Ansh

In [33]:
#tail return last rows
df.tail()

Age  Name
15   30  vans
16   18  shiv
17   22  Ansh
18   60  Ansh
19   78  shiv

In [34]:
df.tail(3)

Age  Name
17   22  Ansh
18   60  Ansh
19   78  shiv

In [35]:
#return shape
df.shape

(20, 2)

In [36]:
# return columns name and type (string is for objects)
df.columns

Index(['Age', 'Name'], dtype='object')

### Accessing DataFrame

In [37]:
df['Name'] # pass column name and will access that column

0     Ansh
1     Ansh
2     shiv
3     Ansh
4     veer
5     Ansh
6     shiv
7     veer
8     Ansh
9     vans
10    veer
11    shiv
12    veer
13    vans
14    vans
15    vans
16    shiv
17    Ansh
18    Ansh
19    shiv
Name: Name, dtype: object

In [38]:
df.info() # Will give you complete Dataframe information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Age     20 non-null     int64 
 1   Name    20 non-null     object
dtypes: int64(1), object(1)
memory usage: 448.0+ bytes


In [39]:
df.describe()

Age
count  20.000000
mean   46.700000
std    24.285798
min    17.000000
25%    25.000000
50%    45.500000
75%    73.250000
max    89.000000

In [40]:
df.set_index('Name',inplace=True)
df

Age
Name     
Ansh   73
Ansh   45
shiv   75
Ansh   49
veer   22
Ansh   26
shiv   74
veer   46
Ansh   89
vans   17
veer   29
shiv   22
veer   48
vans   30
vans   81
vans   30
shiv   18
Ansh   22
Ansh   60
shiv   78

In [41]:
df.sort_index(axis=0, ascending=True)

Age
Name     
Ansh   73
Ansh   45
Ansh   22
Ansh   49
Ansh   26
Ansh   60
Ansh   89
shiv   18
shiv   22
shiv   78
shiv   74
shiv   75
vans   30
vans   81
vans   30
vans   17
veer   29
veer   48
veer   22
veer   46

In [42]:
df = pd.DataFrame({'Num':[1,2,3,4],'value':[444,555,666,444],'text':['abc','def','abc','ght']})
df

Num  value text
0    1    444  abc
1    2    555  def
2    3    666  abc
3    4    444  ght

In [43]:
df['value'].unique()

array([444, 555, 666], dtype=int64)

In [44]:
# number of unique values in columns value
df['value'].nunique()

3

In [45]:
df['value'].value_counts()

444    2
555    1
666    1
Name: value, dtype: int64

In [46]:
def mult(x):
    return x*2

In [47]:
df['Num'].apply(mult)

0    2
1    4
2    6
3    8
Name: Num, dtype: int64

In [48]:
df['Num'].sum()

10

In [49]:
df = pd.DataFrame({'col1': [1,2,3,np.nan],
                   'col2': [np.nan,555,666,444]
})

In [50]:
df

col1   col2
0   1.0    NaN
1   2.0  555.0
2   3.0  666.0
3   NaN  444.0

In [51]:
df.isnull()

col1   col2
0  False   True
1  False  False
2  False  False
3   True  False

In [52]:
# drop null value rows
df.dropna()

col1   col2
1   2.0  555.0
2   3.0  666.0

In [53]:
df = pd.DataFrame({'col1': [1,2,3,np.nan],
                   'col2': [np.nan,555,666,np.nan],
                   'col3': ['qwe','abc','pqr','gdn']
})
df

col1   col2 col3
0   1.0    NaN  qwe
1   2.0  555.0  abc
2   3.0  666.0  pqr
3   NaN    NaN  gdn

In [54]:
# fill null values
df.fillna('ML')

col1 col2 col3
0    1   ML  qwe
1    2  555  abc
2    3  666  pqr
3   ML   ML  gdn

In [55]:
# drop column wise
df.dropna(axis=1)

col3
0  qwe
1  abc
2  pqr
3  gdn

In [56]:
# threshold =2 means drop where 2 nan or more than 2 nan in a single row
df.dropna(thresh = 2)

col1   col2 col3
0   1.0    NaN  qwe
1   2.0  555.0  abc
2   3.0  666.0  pqr

## Reading and writing CSV(Comma Seperated Values)

In [57]:
a = ['2021-06-16', '2021-06-17', '2021-06-18', '2021-06-19',
               '2021-06-20', '2021-06-21', '2021-06-22', '2021-06-23',
               '2021-06-24', '2021-06-25']
b = [23,25,29,30,35,22,22,23,25,16]
c = [6,3,7,3,2,9,5,6,4,3]
d = ['Rain','Sunny','Snow','Snow','Sunny','Fog','Sunny','Snow','Snow','Sunny']

In [58]:
df = pd.DataFrame({'Day':a, 
                   'Temperature':b ,
                   'WindSpeed':c, 
                   'Event':d})
df

Day  Temperature  WindSpeed  Event
0  2021-06-16           23          6   Rain
1  2021-06-17           25          3  Sunny
2  2021-06-18           29          7   Snow
3  2021-06-19           30          3   Snow
4  2021-06-20           35          2  Sunny
5  2021-06-21           22          9    Fog
6  2021-06-22           22          5  Sunny
7  2021-06-23           23          6   Snow
8  2021-06-24           25          4   Snow
9  2021-06-25           16          3  Sunny

In [59]:
# Creating a CSV File
df.to_csv('weather.csv',index=False)

In [60]:
#Read from CSV File
pd.read_csv('weather.csv')

Day  Temperature  WindSpeed  Event
0  2021-06-16           23          6   Rain
1  2021-06-17           25          3  Sunny
2  2021-06-18           29          7   Snow
3  2021-06-19           30          3   Snow
4  2021-06-20           35          2  Sunny
5  2021-06-21           22          9    Fog
6  2021-06-22           22          5  Sunny
7  2021-06-23           23          6   Snow
8  2021-06-24           25          4   Snow
9  2021-06-25           16          3  Sunny

## Reading and writing from and to Excel file

In [61]:
# Creating Excel File from DataFrame
df.to_excel('weather.xlsx', sheet_name='Data', index=False)

In [62]:
#Reading Excel File
pd.read_excel('weather.xlsx')

Day  Temperature  WindSpeed  Event
0  2021-06-16           23          6   Rain
1  2021-06-17           25          3  Sunny
2  2021-06-18           29          7   Snow
3  2021-06-19           30          3   Snow
4  2021-06-20           35          2  Sunny
5  2021-06-21           22          9    Fog
6  2021-06-22           22          5  Sunny
7  2021-06-23           23          6   Snow
8  2021-06-24           25          4   Snow
9  2021-06-25           16          3  Sunny

## Merge and Concat DataFrames

In [63]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                       'B':['B0','B1','B2','B3'],
                       'C':['C0','C1','C2','C3'],
                       'D':['D0','D1','D2','D3'],},
                   index=[0,1,2,3]
                  )
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [64]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                       'B':['B4','B5','B6','B7'],
                       'C':['C4','C5','C6','C7'],
                       'D':['D4','D5','D6','D7'],},
                   index=[0,1,2,3]
                  )
df2

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [65]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                       'B':['B8','B9','B10','B11'],
                       'C':['C8','C9','C10','C11'],
                       'D':['D8','D9','D10','D11'],},
                   index=[0,1,2,3]
                  )
df3

A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [66]:
 pd.concat([df1,df2,df3], axis=0)

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [67]:
left = pd.DataFrame({'Key':['K0','K1','K2','K3'],
                     'A':['A0','A1','A2','A3'],
                     'B':['B0','B1','B2','B3']
                        })
right = pd.DataFrame({'Key':['K0','K1','K2','K3'],
                       'C':['C0','C1','C2','C3'],
                       'D':['D0','D1','D2','D3']
                        })
print(left)
print(right)

  Key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3
  Key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3


In [68]:
pd.merge(left,right,how='inner',on='Key')

Key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3