In [2]:
import numpy as np;
np.array([1,23,4,5])

array([ 1, 23,  4,  5])

In [3]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [4]:
np.arange(1,10,3)

array([1, 4, 7])

### >>**arange() function will take parameters like arange(startindex, endindex, jumpby)**

In [6]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### >>**It will create a matrix of given size with all elements as Zero**

In [8]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### >>It will create a matrix of given size with all elements as 1 

In [9]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### >>*It will create square identity matrix of given size NXN*

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])