In [1]:
import numpy as np;
np.array([1,23,4,5])

array([ 1, 23,  4,  5])

In [2]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [3]:
np.arange(1,10,3)

array([1, 4, 7])

### >>**arange() function will take parameters like arange(startindex, endindex, jumpby)**

In [4]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### >>**It will create a matrix of given size with all elements as Zero**

In [5]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### >>It will create a matrix of given size with all elements as 1 

In [6]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### >>*It will create square identity matrix of given size NXN*

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### >> Declaring datatype to integer of 32 bit by-default it is of type float

In [8]:
np.eye(4, dtype = np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### >> Declaring matrix in the form of array and checking its shape 

In [9]:
a = np.array([[1,2],[3,4],[5,6]])

In [10]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a.shape # used to show shape of array

(3, 2)

In [12]:
np.zeros_like(a) # create matrix of same size as of 'a' but elements are all 0

array([[0, 0],
       [0, 0],
       [0, 0]])

### >> Full is used to create rectangular matrix of elements provided by the user

In [13]:
np.full((3,4),4) # print integer as we are passing integer as input

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [14]:
np.full((3,3),7.7) # Print float type values

array([[7.7, 7.7, 7.7],
       [7.7, 7.7, 7.7],
       [7.7, 7.7, 7.7]])

In [15]:
np.full((4,3),3.2, dtype=np.int32) # Type casting to integer

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### >>np.diag is used to print a diagonal matrix with elements provided inside the brackets

In [16]:
np.diag([1,2,33]) 

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0,  0, 33]])

In [17]:
np.diag(np.arange(6)) # 0 to 5 elements will be as diagonal element

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

### >> tile

#### It simply treats array as a single element and copy it number of time we will pass like (3,3) here

In [18]:
v = np.array([1,2,3,4])
np.tile(v,(3,3)) # 3X3 matrix

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

In [19]:
np.tile(v,(3,1)) # 3X1 matrix where v is a considered as a single element

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### >>Random values

In [20]:
# Give value in between 0 to 1
np.random.random() 

0.6300342588687179

In [21]:
# Firstly it is multiplying matrix with 100 and then taking round to 2 digits after point
a = np.round(np.random.random([3,4]) * 100,2)
a

array([[88.6 , 44.07, 41.51, 88.7 ],
       [76.81, 94.67, 17.85, 73.63],
       [37.99, 62.45, 26.25, 61.12]])

In [22]:
# only select 2 digits after point then multiplying it with 100
b = np.round(np.random.random([3,3]),2)*100 
b

array([[95.,  5., 63.],
       [20., 39., 21.],
       [13., 23., 64.]])

In [23]:
# changing data type from float to int
b.astype(np.int32)

array([[95,  5, 63],
       [20, 39, 21],
       [13, 23, 64]])

### >>Linspace : It divides the range in equal interval ( The growing factor is constant)

In [24]:
np.linspace(1,101,10)

array([  1.        ,  12.11111111,  23.22222222,  34.33333333,
        45.44444444,  56.55555556,  67.66666667,  78.77777778,
        89.88888889, 101.        ])

In [25]:
# return 20 values between 0 to 10
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Performance Measurement

In [26]:
c= range(10000)
%timeit [i**3 for i in c]

9.77 ms ± 706 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
import numpy as np
c = np.arange(10000)
%timeit c**3

51.9 µs ± 5.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


### >>Reshape the list

In [28]:
np.arange(10).shape # Return the shape of the array

(10,)

In [29]:
np.arange(20).reshape(5,4) # This will reshape the array into matrix of given size

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

#### Note: If you provide unmatched matrix size then it will throw an error

In [30]:
''' if you only want to provide rows and don't want to pass column then simply pass (row,-1) 
    and similear on column side (-1,column) '''
np.arange(20).reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [31]:
np.arange(20).reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [32]:
a = np.array([3,5,2,8,1,0,9,4,7,8,3])
a

array([3, 5, 2, 8, 1, 0, 9, 4, 7, 8, 3])

In [33]:
a[3] # accessing a single element

8

In [34]:
a[[2,3,4,6]] #accessing multiple elements from array

array([2, 8, 1, 9])

In [35]:
a[:4]

array([3, 5, 2, 8])

In [36]:
a[0:9:2] #startindex : endindex : jumpby 

array([3, 2, 1, 9, 7])

In [37]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.shape

(3, 3)

In [38]:
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [39]:
#getting value from the array which satifies the condition
b = a>3
print(b)
a[b]

[[False False False]
 [ True  True  True]
 [ True  True  True]]


array([4, 5, 6, 7, 8, 9])

In [40]:
a = np.arange(10)
print("A Before : ",a)
b = a
print("B before : ",b)
b[0] = 32
print("B after: ",b)
print("A after: ",a)
# B and A are sharing same memory space if we update "b" changes will reflect in 'a' also

np.shares_memory(a,b) # check whether they shares same memory or not

A Before :  [0 1 2 3 4 5 6 7 8 9]
B before :  [0 1 2 3 4 5 6 7 8 9]
B after:  [32  1  2  3  4  5  6  7  8  9]
A after:  [32  1  2  3  4  5  6  7  8  9]


True

In [41]:
print(id(a)) # id function used to display address
id(b)

2062555922880


2062555922880

In [42]:
a = np.arange(9)
b = a.copy() # different memory address
c = a[:]     # assign seperate memory
print(a)
print(b)
print(c)
print(id(a))
print(id(b))
print(id(c))

[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7 8]
2062555812528
2062555813088
2062555922880


### Transpose

In [43]:
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [44]:
a.T #Transpose of a

array([[1, 4],
       [2, 5],
       [3, 6]])

## Trignometric functons in numpy

In [45]:
#sin
a = np.arange(10)
print(a)
print("Sin :",np.sin(a))
print("Cos :",np.cos(a))
print("Tan :",np.tan(a))

[0 1 2 3 4 5 6 7 8 9]
Sin : [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
Cos : [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
Tan : [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]


In [46]:
#exponential
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

## Mathematics functions

In [47]:
np.sum(a)

45

In [48]:
np.median(a)

4.5

In [49]:
np.mean(a)

4.5

In [50]:
a.std() #standard deviation

2.8722813232690143

## Linear Algebra

In [51]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
# Determinant
np.linalg.det(a)

-9.51619735392994e-16

In [53]:
# inverse matrix
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [54]:
#Transpose
b = a.T
print (a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [55]:
# Matrix Dot product
np.dot(a,b)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

## Logical gates

In [56]:
a = np.array([1,0,1], dtype=bool)
a

array([ True, False,  True])

In [57]:
b = np.array([0,1,1], dtype=bool)
b

array([False,  True,  True])

In [58]:
np.logical_or(a,b) # logical OR

array([ True,  True,  True])

In [59]:
np.logical_and(a,b) # logical AND gate

array([False, False,  True])

## Array sum 

In [60]:
a= np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
a.sum() #sum of all elements

21

In [62]:
a.sum(axis=0) # sum of columns

array([5, 7, 9])

In [63]:
a.sum(axis=1) # sum of rows

array([ 6, 15])

In [64]:
a.max() # max element

6

In [65]:
a.argmax() # maximum element is present at index 5

5

In [66]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a.shape

(9,)

In [68]:
a[:,np.newaxis].shape

(9, 1)

### sort

In [69]:
a = np.array([1,8,4,6,3,2,0])
a

array([1, 8, 4, 6, 3, 2, 0])

In [70]:
np.sort(a) #sort based on values of array

array([0, 1, 2, 3, 4, 6, 8])

In [71]:
np.argsort(a) #sort based on arg position

array([6, 0, 5, 4, 2, 3, 1], dtype=int64)