In [2]:
import numpy as np;
np.array([1,23,4,5])

array([ 1, 23,  4,  5])

In [3]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [4]:
np.arange(1,10,3)

array([1, 4, 7])

### >>**arange() function will take parameters like arange(startindex, endindex, jumpby)**

In [6]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### >>**It will create a matrix of given size with all elements as Zero**

In [8]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### >>It will create a matrix of given size with all elements as 1 

In [9]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

### >>*It will create square identity matrix of given size NXN*

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### >> Declaring datatype to integer of 32 bit by-default it is of type float

In [8]:
np.eye(4, dtype = np.int32)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### >> Declaring matrix in the form of array and checking its shape 

In [9]:
a = np.array([[1,2],[3,4],[5,6]])

In [10]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
a.shape # used to show shape of array

(3, 2)

In [14]:
np.zeros_like(a) # create matrix of same size as of 'a' but elements are all 0

array([[0, 0],
       [0, 0],
       [0, 0]])

### >> Full is used to create rectangular matrix of elements provided by the user

In [16]:
np.full((3,4),4) # print integer as we are passing integer as input

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [17]:
np.full((3,3),7.7) # Print float type values

array([[7.7, 7.7, 7.7],
       [7.7, 7.7, 7.7],
       [7.7, 7.7, 7.7]])

In [18]:
np.full((4,3),3.2, dtype=np.int32) # Type casting to integer

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

### >>np.diag is used to print a diagonal matrix with elements provided inside the brackets

In [19]:
np.diag([1,2,33]) 

array([[ 1,  0,  0],
       [ 0,  2,  0],
       [ 0,  0, 33]])

In [20]:
np.diag(np.arange(6)) # 0 to 5 elements will be as diagonal element

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

### >> tile

#### It simply treats array as a single element and copy it number of time we will pass like (3,3) here

In [26]:
v = np.array([1,2,3,4])
np.tile(v,(3,3)) # 3X3 matrix

array([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
       [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])

In [29]:
np.tile(v,(3,1)) # 3X1 matrix where v is a considered as a single element

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### >>Random values

In [31]:
# Give value in between 0 to 1
np.random.random() 

0.9401826302260091

In [37]:
# Firstly it is multiplying matrix with 100 and then taking round to 2 digits after point
a = np.round(np.random.random([3,4]) * 100,2)
a

array([[42.17, 68.68, 74.48, 24.81],
       [56.3 , 64.2 , 17.12, 52.24],
       [53.12, 60.17, 92.51, 35.95]])

In [45]:
# only select 2 digits after point then multiplying it with 100
b = np.round(np.random.random([3,3]),2)*100 
b

array([[25., 38.,  2.],
       [41., 17., 45.],
       [80., 76., 11.]])

In [46]:
# changing data type from float to int
b.astype(np.int32)

array([[25, 38,  2],
       [41, 17, 45],
       [80, 76, 11]])

### >>Linspace : It divides the range in equal interval ( The growing factor is constant)

In [56]:
np.linspace(1,101,10)

array([  1.        ,  12.11111111,  23.22222222,  34.33333333,
        45.44444444,  56.55555556,  67.66666667,  78.77777778,
        89.88888889, 101.        ])

In [55]:
# return 20 values between 0 to 10
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])